name: Retire Artifacts
on:
  schedule:
    - cron: '0 3 * * 1'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run Agent
        run: python agent/run.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
          AZDO_PAT: ${{ secrets.ADO_PAT }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}